### ISSUE TITLE
Docs are broken

### ISSUE THREAD

**Issue by janhohenheim** [gschup/bevy_ggrs#23]
**Describe the bug**
The newest docs are broken

**To Reproduce**
1. Go to https://docs.rs/crate/bevy_ggrs/latest

**Expected behavior**
I see the newest docs

**Screenshots**
<img width="852" alt="image" src="https://user-images.githubusercontent.com/9047632/168376241-e5e32dc5-53b5-4366-9e4e-a4617dc475bf.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser [e.g. chrome, safari]: Firefox Nightly
 - Version [e.g. 22]: 101.0a1 (2022-04-29)

**Additional context**
Last working docs were 0.1.3

**Comment by gschup** [comment]
Thanks for the report. Looking into the build logs on docs.rs, this seems to be a problem with bevy_ecs on nightly rust, which is used there.

```
[INFO] [stderr]     Checking bevy_ecs v0.6.0
[INFO] [stderr] error: format argument must be a string literal
[INFO] [stderr]    --> /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.6.0/src/schedule/executor_parallel.rs:135:66
[INFO] [stderr]     |
[INFO] [stderr] 135 | ...                   .unwrap_or_else(|error| unreachable!(error));
[INFO] [stderr]     |                                                            ^^^^^
[INFO] [stderr]     |
[INFO] [stderr] help: you might be missing a string literal to format with
[INFO] [stderr]     |
[INFO] [stderr] 135 |                             .unwrap_or_else(|error| unreachable!("{}", error));
[INFO] [stderr]     |                                                                  +++++
[INFO] [stderr] 
[INFO] [stderr] error: format argument must be a string literal
```

If I run `cargo doc --open` locally, using stable rust, the docs build just fine. Small disclaimer: As it stands, `bevy_ggrs` plugin does not have very good documentation. I recommend checking out the examples or the documentation of `ggrs` itself.

**Comment by gschup** [comment]
While I was unable to resolve the issue for 0.9, bevy_ggrs 0.10 has built docs on docs.rs
