### ISSUE TITLE
Invalidated Entities

### ISSUE THREAD

**Issue by zicklag** [gschup/bevy_ggrs#40]
I just found that invalidating entities is still an issue, ~~but luckily I also discovered the fix we need in the `bevy_hierarchy` crate~~. Just posting here for a heads-up in case anybody runs into it:

https://github.com/bevyengine/bevy/issues/6790

For now, in my game I've just patched Bevy with the PR linked in the issue above to fix it.

_Originally posted by @zicklag in https://github.com/gschup/bevy_ggrs/issues/29#issuecomment-1329993581_

---

I'm re-opening this issue because the fix I opened in Bevy wasn't accepted, because it could cause hierarchy inconsistencies. That's a valid point, but we _need_ the behavior I added to make our entity updates work right.

I think what we have to do is we have to make a `RollbackMapEntities` trait that works essentially similar to the `MapEntities` trait, but with a slight behavior change, that we can implement for `Parent` and `Children` and that users can implement for their own component types that need entity mapping.

**Comment by johanhelsing** [comment]
I think we added a workaround for this in #74, if I understand this issue correctly. Should we close?

**Comment by gschup** [comment]
I think yes! We can always reopen if this issue pops up again.
