### ISSUE TITLE
Potential Scalability Refactor

### ISSUE THREAD

**Issue by eatjason** [gschup/bevy_ggrs#47]
Hello,

I am happy to have stumbled upon this project, I have been working on a GGPO like project that takes the GGPO algorithm to the next level so it can be scaled up and used for games that have 1000's of units.  It does this by having a never rewind policy.  Basically the official correct state is never stepped forward until it has the complete input for that frame.  Then to remove lag, the current frame is rendered by taking a snapshot of the most recent official state, and fast forwarding a subset of the game state (for example, objects only visible or potentially visible on the players screen in the next 300 milliseconds).  The local player input is inserted into these fast forwarded frames, and the remote player inputs are guessed.

I have written an article about this technique:  http://retroprose.net/2021/06/10/universal-netcode-framework/
And here is an example of it in action:  http://retroprose.net/files/hurkle/

That demo uses unity and csharp, but I ported it to Rust and still need to port the networking code and stumbled on this plug in for bevy.  I noticed there is still some lag in my demo, but that may just be unity input lag or something with my server (a free tier Rander server running Go).

The demo uses all integer math to get determinism.  I'm still in the process of evaluating bevy to determine if I can create deterministic code with floating point math or fixed point math.  

I noticed that some bevy changes may force this project to get refactored anyway, I thought this article may spark some ideas for how to apply the GGPO algorithm in a new way.

**Comment by gschup** [comment]
Hi, 

thanks for post :) This repo handles only the plugin for bevy. the core functionality is found in [gschup/ggrs](https://github.com/gschup/ggrs).

If you are interested talking about the inner workings of GGRS, I recommend going over there. This plugin is just a connecting layer between ggrs and bevy.

**Comment by gschup** [comment]
Cool article :)

About your technique: No matter if you call it rolling back from the current state or stepping ahead of the confirmed state, the result is the same if you advance the whole state. The key difference to me seems that you advance only a subset of the state forward instead of advancing the whole state. Sounds like a cool idea for certain types of applications!

My questions with your approach: 
- Do you have to do multiple, local steps forward every render frame, starting from the "ground truth" in every render step?
- When is figuring out which part of the state to step forward cheaper than stepping forward the whole state?

**Comment by eatjason** [comment]
You are right about the nomenclature and about it being the same.  I was trying to design the system in such a way that you can write your game without touching netcode at all, with the one exception of overwriting two functions: your substate copy, and your fast forward update.  Then you would have the option of letting them default to copying the entire state, and just running the same update function as the game itself on the copied state.  Which the default is only possible with what you have observed is that the result is exactly the same, with the exception of performance.  

To answer your questions:

- There are multiple local steps forward every frame starting from the ground truth just as you said.
- Figuring out the substate to step forward is cheaper when you have a large state.  Say for example you made a game that has as many active units as StarCraft 2.  Simulating 5000 units multiple times per frame will be slower than taking about 100 on the local player's screen.  Also to note, in my design you could opt out of the fast forward all together if its something like a strategy game and a few 100 millisecond delay in input isn't noticeable.  

I'm a little fuzzy on what the GGPO code actually does.  I figured this plug in is where the substate copy techinique might be relevant, because bevy is where the state is held.  

It is also interesting to note that this essentially what client-server netcode does in may cases, they send a frame (or in this case substate) and predict the state from the substate contained as a frame, except in this case we are getting the substate locally from the "ground truth".   

The rethinking of the nomenclature of rewinding and fast forwarding helped me see that really all architectures are doing the same thing, they are just transferring that information differently.

So one question I have is does the core functionality take care of game state, or does it just manage the input and network streams?

**Comment by gschup** [comment]
Most basic things about ggrs are explained [in the wiki](https://github.com/gschup/ggrs/wiki/).

In each game loop tick, you register inputs for local players and then try to advance a step. If that succeeds, you will get back a list of [requests](https://github.com/gschup/ggrs/wiki/4.-Requests-and-Events). The requests tell you when and what to load, when to advance your game state or when to save your game state. All requests carry in them some parameters that give context. For loading and saving requests, you get passed a `GameStateCell<T::State>`. You can use this provided buffer to save your state, but you can also just do it yourself outside of GGRS. 

Take a look at an exemplary main loop [here](https://github.com/gschup/ggrs/wiki/3.-Main-Loop).

Generally speaking, it is up to the user of the library to implement how they handle these requests ([example](https://github.com/gschup/ggrs/blob/d5313dc334277d484273ecf1a428f5da5e269639/examples/ex_game/ex_game.rs#L76))

**Comment by eatjason** [comment]
That is interesting, I didn't factor in that if the input is predicted correctly, you can avoid rolling back.  I just assumed it would rarely be correct.

I did notice that actually it would be correct in between button presses because a lot of the time players are just holding buttons.  I didn't bother with this optimization because I figured if it can't simulate multiple simulation frames per render frame, it would slow down when players do complex input and needs lots of correction.  And if its not complex you would just complete the frame faster when predicted correctly, but then just wait, so might as well just recalculate every frame.

I'll take a closer look at [gschup/ggrs](https://github.com/gschup/ggrs), maybe I can just write my own plugin that does what I want it to do.  

Thanks!

**Comment by gschup** [comment]
The prediction is right in a surprising high amount of cases. This is mostly due to the fact that a game running at 60 FPS far exceeds the speed of inputs players make. Even if you consider some extreme case of players doing [10 inputs per second](https://www.nbcnews.com/technolog/how-fast-fast-some-pro-gamers-make-10-moves-second-8c11422946), in 50 of those 60 frames the input is the same as it was the previous frame.
