### ISSUE TITLE
When rollbacks happen across entity spawning, desyncs are reported

### ISSUE THREAD

**Issue by johanhelsing** [gschup/bevy_ggrs#81]
**Describe the bug**

When rollbacks happen across entity spawning, desyncs are reported

**To Reproduce**

Run the example from #78 with `--input-delay 0`

Press space a couple of times, observe a desync being reported.

**Expected behavior**

No desyncs reported

**Additional information**

I'm not sure if this is a real desync or a false positive.

Related to #79 same steps to repro, perhaps the same root cause as well.

**Comment by bushrat011899** [comment]
I suspect this issue can now be closed since #82 has been merged.
