### ISSUE TITLE
bevy 0.12

### ISSUE THREAD

**Issue by solnyszczko** [gschup/bevy_ggrs#84]
New bevy version has released, a potential source of breakage could be the new Time system, which changes how FixedUpdate works slightly.

https://bevyengine.org/learn/migration-guides/0.11-0.12/#unify-fixedtime-and-time-while-fixing-several-problems

**Comment by gschup** [comment]
This is already being approached by PR #83. We hope it lands on main soon :)

**Comment by solnyszczko** [comment]
oops im a dummy, awesome work !!! woooooo
